sonar.projectKey=Hugo-BSilva_Projeto-Web-MVC-ASP.NET-Core
sonar.organization=devcodehugo
sonar.sources=SalesWebMVC
sonar.exclusions=**/bin/**,**/obj/**,**/*.csproj,**/*.sln
sonar.sourceEncoding=UTF-8
